// <auto-generated />
using System;
using Arise.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Arise.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AriseDbContext))]
    [Migration("20260724205838_AjoutDesProfilsDeProgression")]
    partial class AjoutDesProfilsDeProgression
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:CollationDefinition:insensible_a_la_casse", "und-u-ks-level2,und-u-ks-level2,icu,False")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Arise.Domain.Hunters.HunterProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CurrentXp")
                        .HasColumnType("integer")
                        .HasColumnName("current_xp");

                    b.Property<DateOnly?>("LastCompletionDate")
                        .HasColumnType("date")
                        .HasColumnName("last_completion_date");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("rank");

                    b.Property<int>("StreakCurrent")
                        .HasColumnType("integer")
                        .HasColumnName("streak_current");

                    b.Property<int>("StreakLongest")
                        .HasColumnType("integer")
                        .HasColumnName("streak_longest");

                    b.Property<int>("XpToNextLevel")
                        .HasColumnType("integer")
                        .HasColumnName("xp_to_next_level");

                    b.HasKey("Id")
                        .HasName("pk_hunter_profiles");

                    b.ToTable("hunter_profiles", (string)null);
                });

            modelBuilder.Entity("Arise.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<DateTimeOffset>("RegisteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("username")
                        .UseCollation("insensible_a_la_casse");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
