// <auto-generated />
using System;
using Arise.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Arise.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AriseDbContext))]
    [Migration("20260728193211_RattachementDuProfilAuCompte")]
    partial class RattachementDuProfilAuCompte
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:CollationDefinition:insensible_a_la_casse", "und-u-ks-level2,und-u-ks-level2,icu,False")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Arise.Domain.Habits.Habit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("frequency");

                    b.Property<Guid>("HunterProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("hunter_profile_id");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("name")
                        .UseCollation("insensible_a_la_casse");

                    b.HasKey("Id")
                        .HasName("pk_habits");

                    b.HasIndex("HunterProfileId")
                        .HasDatabaseName("ix_habits_hunter_profile_id");

                    b.HasIndex("HunterProfileId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_habits_hunter_profile_id_name")
                        .HasFilter("NOT is_archived");

                    b.ToTable("habits", (string)null);
                });

            modelBuilder.Entity("Arise.Domain.Habits.HabitLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date")
                        .HasColumnName("day");

                    b.Property<Guid>("HabitId")
                        .HasColumnType("uuid")
                        .HasColumnName("habit_id");

                    b.Property<DateTimeOffset>("LoggedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("logged_at");

                    b.HasKey("Id")
                        .HasName("pk_habit_logs");

                    b.HasIndex("HabitId", "Day")
                        .IsUnique()
                        .HasDatabaseName("ix_habit_logs_habit_id_day");

                    b.ToTable("habit_logs", (string)null);
                });

            modelBuilder.Entity("Arise.Domain.Hunters.HunterProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CurrentXp")
                        .HasColumnType("integer")
                        .HasColumnName("current_xp");

                    b.Property<DateOnly?>("LastCompletionDate")
                        .HasColumnType("date")
                        .HasColumnName("last_completion_date");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("rank");

                    b.Property<int>("StreakCurrent")
                        .HasColumnType("integer")
                        .HasColumnName("streak_current");

                    b.Property<int>("StreakLongest")
                        .HasColumnType("integer")
                        .HasColumnName("streak_longest");

                    b.Property<int>("XpToNextLevel")
                        .HasColumnType("integer")
                        .HasColumnName("xp_to_next_level");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_hunter_profiles");

                    b.ToTable("hunter_profiles", (string)null);
                });

            modelBuilder.Entity("Arise.Domain.Quests.Quest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("description");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("difficulty");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("domain");

                    b.Property<Guid>("HunterProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("hunter_profile_id");

                    b.Property<bool>("IsFallback")
                        .HasColumnType("boolean")
                        .HasColumnName("is_fallback");

                    b.Property<DateOnly>("QuestDate")
                        .HasColumnType("date")
                        .HasColumnName("quest_date");

                    b.Property<string>("StatTarget")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("stat_target");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<int>("XpReward")
                        .HasColumnType("integer")
                        .HasColumnName("xp_reward");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_quests");

                    b.HasIndex("HunterProfileId", "Domain", "QuestDate")
                        .IsUnique()
                        .HasDatabaseName("ix_quests_hunter_profile_id_domain_quest_date");

                    b.ToTable("quests", (string)null);
                });

            modelBuilder.Entity("Arise.Domain.Tasks.TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<Guid>("HunterProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("hunter_profile_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_tasks");

                    b.HasIndex("HunterProfileId")
                        .HasDatabaseName("ix_tasks_hunter_profile_id");

                    b.ToTable("tasks", (string)null);
                });

            modelBuilder.Entity("Arise.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("HunterProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("hunter_profile_id");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<DateTimeOffset>("RegisteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("username")
                        .UseCollation("insensible_a_la_casse");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("HunterProfileId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_hunter_profile_id")
                        .HasFilter("hunter_profile_id IS NOT NULL");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Arise.Domain.Habits.Habit", b =>
                {
                    b.HasOne("Arise.Domain.Hunters.HunterProfile", null)
                        .WithMany()
                        .HasForeignKey("HunterProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_habits_hunter_profiles_hunter_profile_id");
                });

            modelBuilder.Entity("Arise.Domain.Habits.HabitLog", b =>
                {
                    b.HasOne("Arise.Domain.Habits.Habit", null)
                        .WithMany()
                        .HasForeignKey("HabitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_habit_logs_habits_habit_id");
                });

            modelBuilder.Entity("Arise.Domain.Quests.Quest", b =>
                {
                    b.HasOne("Arise.Domain.Hunters.HunterProfile", null)
                        .WithMany()
                        .HasForeignKey("HunterProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_quests_hunter_profiles_hunter_profile_id");
                });

            modelBuilder.Entity("Arise.Domain.Tasks.TaskItem", b =>
                {
                    b.HasOne("Arise.Domain.Hunters.HunterProfile", null)
                        .WithMany()
                        .HasForeignKey("HunterProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tasks_hunter_profiles_hunter_profile_id");
                });
#pragma warning restore 612, 618
        }
    }
}
